### PR TITLE
add rpc method to controller

### PR DESCRIPTION
**Pull request by galenwarren**

### CODE REVIEW

**Comment by jeffijoe** [comment]
Hey @galenwarren, since `.rpc` is synonymous with `.all`, isn't it confusing to have 2 calls do the same thing? What's the use case? 😄

**Comment by galenwarren** [comment]
Oops, I actually meant to merge this into my own fork, sorry about that. But as long as I've opened this pull request here ...

First, thanks for the awilix library, I think it's great and have used it in a few projects, along with awilix-koa. I'm working on a grpc project, using [groa](https://github.com/GroaJS/groa) now and am building an [awilix-groa](https://github.com/galenwarren/awilix-groa) library that will do the same for groa as awilix-koa does for koa. Groa has a [groa-router](https://github.com/GroaJS/groa-router) companion project that enables one to define grpc methods using familiar router syntax. This pull request just adds an .rpc method to the controller that can be used to define rpc methods (and internally it's just a synonym for .all).

Let me know what you think ... thanks.

**Comment by galenwarren** [comment]
Also, should have said that the .rpc method would mirror the way that .rpc methods are defined in groa-router, or any rpc router. I suppose that one could use .all there as well but that doesn't really mean anything in the rpc sense (there are no really no "verbs" in rpc so .all doesn't quite make sense there).

**Comment by jeffijoe** [comment]
If you think the `grpc` usage can be mapped using this package without it seeming like a hack then go for it, however I think we should stick to `.all` but keep the modifications to the README indicating that it could be used for both. 😄

I'm not familiar with `grpc`, it sounds like it wouldn't really fit into the http model?

I'm gonna take a look at this, feel free to add a PR with a link to your bindings when ready!

**Comment by jeffijoe** [comment]
After taking a closer look, I think it makes more sense for you to build the controller stuff into your `awilix-groa` bindings rather than trying to shoehorn the ones from this package (as they are meant for http). Sadly there's not really a generic transport-agnostic way here without making sacrifices (for example, Feathers attempts to be transport-agnostic but forces it's users to stick to a CRUD model).

Feel free to lift the state management utilities from this package though!

What do you think?

**Comment by galenwarren** [comment]
All good points, thanks. I *think* I can make use of this library, in conjunction with groa-router, but that's still not proven -- like I said, I didn't mean to submit the PR to you yet :). I'll close this PR and do some work on my own and then get back in touch if/when I have something more concrete to propose. Thanks again.

**Pull request closed without merging**
